### PR TITLE
Sancus example changes for compiler changes

### PR DESCRIPTION
**Pull request by fritzalder**
This finally also modifies the sancus examples for https://github.com/sancus-tee/sancus-compiler/pull/33 .
Included in the PR are: 
 - New confidential loading example that does not work with Aion
 - Modified hello-world example that is now simpler
 - New timer-single-sm example that showcases the new sm-config.yml file type

There are also still a few issues with this PR (maybe incomplete):
- [ ] In Aion, CPUOFF can not be switched when at least one SM is loaded. This affects (at least) the examples arithmetic, dma, fileio, sancus-step, sensor-reader
- [ ] dma does seem to work
- [ ] fileio stalls
- [ ] timer stalls
- [x] Expect failure in GH actions for violations and atomic-violations examples.
- [x] Figure out a good way to deal with atomic_violation that should fail on Aion but not on normal Sancus

I did not do a complete look yet since we need to solve the first issue before tackling the rest. We have multiple options:
1. Always disable all SMs at the end of the example (good practice) and then call exit
2. Call exit from SM with ID 1 (privileged in Aion, so that would work).
I prefer option 1 but wanted to hear what you think before I make the changes.

### CODE REVIEW

**Comment by fritzalder** [comment]
Also, some examples expect to fail (atomic-violation, violation). So we should also mark this in the GH actions workflow.

**Comment by jovanbulck** [comment]
Thanks @fritzalder for the PR! I'm think we probably want to tackle this in 2 stages:

1. make sure sancus-examples work again with the newest sancus-compiler and sancus-core, but configured *without* Aion changes (i.e., a sancus-core with the default `ATOMICITY_MONITOR=0` as will be provided in the sancus-core64-128 packages built by sancus-main)
2. once this works, provide an aion-core-128 in sancus-main and extend the build matrix and update the examples to work with this (as you partially outline above) + exclude tests like conf-loading that are not supported in this config

**Comment by jovanbulck** [comment]
Not sure, can we maybe split some of the changes here to first implement step 1 to make reviewing easier?

eg atomic-violation is only relevant for step 2 right?

maybe a separate PR for the hello-world and conf-loading

and a separate PR for the timer ISR example?

**Comment by fritzalder** [comment]
I honestly disagree with the multi step approach and would also not overengineer this PR. Sure, it is not the nicest approach to do it in one go but these are also just some basic examples. I don't think we need to discuss in-depth what each example does, so once the PRs in core and compiler are merged, I would just make sure that each of these examples run fine. Feel free to still split some of the new examples into new PRs if you want but alternatively just modify or delete them as you wish in this PR - that would be fastest.

**Comment by jovanbulck** [comment]
Im afraid it'll be more complex than it seems cause we have far-going changes affecting the example, but we can indeed wait and see if it breaks or not.

IMO we don't really have a choice but to do it multi-step: we don't have an aion-core-128 container yet to test on, so let's first get things working in step (1) and then start looking into aion-compatibility (step 2)

**Comment by jovanbulck** [comment]
the current design with a single ocall_id doesn't work when considering nested ecalls (where an SM can call back into the caller SM which may itself call other SMs again, which is possible in C function calls and with the current stubs). If we want to support that we prob need to save them on the stack.

The bigger issue is that we cannot guarantee thread isolation in this case:

eg consider 2 mutually distrusting threads: T1 with enclaves A-B and T2 with enclave C

A -ecall-> B ; IRQ, scheduler; C -ecall-> A ; IRQ, scheduler; A reti, will now start working for thread T2 on the time budget of T1 (!)

I don't see an easy solution for this (apart from maintaining a threadID as I did in my earlier availability prototype) or disallowing nested ecalls altogether (ie a type of restricted call graph without backarrows, which puts some burden on the programmer, but can be enforced in the stub I think)

**Comment by jovanbulck** [comment]
many thanks @fritzalder ! It seems the examples mostly work now (at least they all check on sancs-core), but there seems to be an issue with sancus-step something with an unexpected crypto-irq that causes it to fail silently. I'll try to look into this further

**Comment by fritzalder** [comment]
Yes, it's looking quite good already. The things that are currently not working yet:
- timer uses the sm_isr.S stub that we did not update yet (ironically)
- Not sure what happens to timer-single-sm but I can look into that
- arithmetic and I think also some of the others fail in aion because EXIT() does not work outside of SM ID 1

**Comment by jovanbulck** [comment]
> Yes, it's looking quite good already. The things that are currently not working yet:
> 
>     * timer uses the sm_isr.S stub that we did not update yet (ironically)

hm `timer` is simply an unprotected ISR right? Afais it works as expected on sancus-core and the problem on aion-core is the EXIT() I guess

> 
>     * Not sure what happens to timer-single-sm but I can look into that

okay great! From what I understood, this is an example to showcase SM-private timer and ISRs right? should we maybe rename it to something like `timer-exclusive` or `timer-protected` or so to make this more clear?

> 
>     * arithmetic and I think also some of the others fail in aion because EXIT() does not work outside of SM ID 1

aha makes sense indeed, then we should either move the EXIT inside the SM or have another way of stopping the simulation in the verilator top-level file I guess :thinking:

**Comment by jovanbulck** [comment]
@fritzalder I tried updating the examples to call exit from within SM1. One thought, can we simply provoke a violation in the aion-core when updating CPUOFF outside of SM1? That will also ensure that the simulator stops on failing  ASSERT()s..

**Comment by fritzalder** [comment]
I updated the protected timer example. The core issue that sm_isr.s in the compiler modifies __sm_sp which is not necessary anymore and in this case even results in succeeding calls as being falsefully recognized as returns. When removing that line, the protected code works again. I honestly wonder why the non-aion cores do not have the same issue, something is weird there. I opened https://github.com/sancus-tee/sancus-compiler/pull/39

**Comment by jovanbulck** [comment]
Fixed some issues in the core and sancus-step is now working :tada: 

As far as I see almost all tests are now passing, expect timer-aion and dma-aion. Any idea what's going wrong there? Maybe not exiting correctly?

**Comment by jovanbulck** [comment]
hm for the DMA one, since we changed the sm_entry stubs I think the problem will be that the hard-coded `INSTRUCTION_NUMBER_JMP` needs to be updated. I can look into that later. The test should simply fail, but  Iguess the assert never finishes cause EXIT is ignored outside of SM1..

@fritzalder can we modify the core to simply throw a violation when doing EXIT/CPUOFF; will this cleanly abort the simulation when a violation handler is not registered? We should think of an easy solution here, maybe another `sancus-sim` flag, so we can at least see the errors and they don't timeout..

**Comment by jovanbulck** [comment]
> hm for the DMA one, since we changed the sm_entry stubs I think the problem will be that the hard-coded `INSTRUCTION_NUMBER_JMP` needs to be updated. I can look into that later. The test should simply fail, but Iguess the assert never finishes cause EXIT is ignored outside of SM1..
> 
> @fritzalder can we modify the core to simply throw a violation when doing EXIT/CPUOFF; will this cleanly abort the simulation when a violation handler is not registered? We should think of an easy solution here, maybe another `sancus-sim` flag, so we can at least see the errors and they don't timeout..

I updated sancus-support for this. it runs locally, now re-building docker images on gh actions..

**Comment by jovanbulck** [comment]
all green now, this is ready for merging! :heavy_check_mark: 

I think this completes the Aion merge (the remaining issue in sancus-core has also been fixed by reverting the extra wait cycle now that the root issue in verilator is fixed).

Many thanks @fritzalder, it was a lot of work but I'm very happy we could successfully incorporate such major changes upstream! Let's celebrate the merge completion later! :tada: :tada:

**Pull request merged**
